apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: montecarlo-results
  labels:
    app: montecarlo-gpu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
